spring:
  datasource:
    url: jdbc:h2:mem:H2DB
    username: sa
    password: 123
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
hibernate:
  dialect: org.hibernate.dialect.H2Dialect
