spring:
  datasource:
   url: jdbc:h2:mem:H2DB
   username: sa
   password: 123
   driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
hibernate:
  dialect: org.hibernate.dialect.H2Dialect
